### ISSUE TITLE
End the lesson - domain

### ISSUE THREAD

**Issue by krzykrucz** [krzykrucz/e-lesson#12]

**Comment by jakubiec** [comment]
@krzykrucz how are we going to represent `Bells` ? It's required to check if bell already rang before finishing the lesson. I can implement it as a dependency with some `dumb` implementation though

**Comment by krzykrucz** [comment]
> @krzykrucz how are we going to represent `Bells` ? It's required to check if bell already rang before finishing the lesson. I can implement it as a dependency with some `dumb` implementation though

just check if now is no later than 45 minutes after lesson hour number start time (it's inside the lesson)

**Comment by jakubiec** [comment]
>just check if now is no later than 45 minutes after lesson hour number start time (it's inside the lesson)

@krzykrucz according to model, I guess the input to FinishWorkflow process should be InProgressLesson and Time but InProgressLesson doesn't have lesson hour number, did I understand it correctly?

**Comment by jakubiec** [comment]
nvm, I found the way
