### ISSUE TITLE
Add `nextExercise` script

### ISSUE THREAD

**Issue by FatCaterpillar** [krzykrucz/e-lesson#50]
Having an ability to call `nextExercise` either from Gradle or from bash script is a very convenient way of going through exercises. What would be extra-awesome is to have `pullOriginalSolution` and `prevExercise` commands.

**Comment by krzykrucz** [comment]
`pullOriginalSolution ` probably will not be needed (we don't want to expose the full project before the end of the workshops and the solution to the current exercise will be included in the next exercise already)
